### ISSUE TITLE
version 1.0.0

### ISSUE THREAD

**Issue by c-nv-s** [mig1984/bashible#8]
I'm interested in starting to roll out some bashible for some general use cases.
It would be nice to get an idea of when you think you'll have a fairly stable version baselined, just so I can understand if there will be breaking changes if I update.
I know you were still adapting it based on a couple of feedback points received.

**Comment by mig1984** [comment]
Hi, 

I am about to publish bashible 0.0.4. It's far to have stable syntax, but at least i already use it in my projects.
I always use the file including the version /usr/local/bin/bashible-0.0.4, so it won't break something in the future.

Jan
