### ISSUE TITLE
Inherit errexit

### ISSUE THREAD

**Issue by polyrand** [mig1984/bashible#9]
In this line you mention `set -e` in subprocesses created by the script:

https://github.com/mig1984/bashible/blob/846919df6e30f5ab5f22a7a29ac9cfc4f05c12b9/bashible#L230

I'm not sure if I completely understand what you mean by that, but maybe adding this can work?:

```bash
shopt -s inherit_errexit 2>/dev/null || true
````

This makes subprocesses inherit errexit. But maybe I'm confused and you were not referring to that.

I just discovered this project and I find it amazing. Thanks for the work!

**Comment by mig1984** [comment]
hi, thanks, it's done

**Comment by ootada** [comment]
running bashible i get:
``` ./bashible: line 574: shopt: inherit_errexit: invalid shell option name ```

bash manual says this shopt is only available in posix mode
